# Generated by Django 5.2.6 on 2025-09-09 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('discount_kind', models.CharField(choices=[('percent', 'percent'), ('fixed', 'fixed')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_cart', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('per_customer_limit', models.IntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('salla_coupon_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='core.merchant')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'indexes': [models.Index(fields=['expires_at'], name='coupons_cou_expires_292eae_idx')],
                'constraints': [models.UniqueConstraint(fields=('merchant', 'code'), name='uq_coupon_code_per_merchant')],
            },
        ),
    ]
