# Generated by Django 5.2.6 on 2025-10-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='exclude_discounted',
            field=models.BooleanField(default=False, verbose_name='استثناء المنتجات المخفضة'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='free_shipping',
            field=models.BooleanField(default=False, verbose_name='مع شحن مجاني ؟'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='المبلغ الأقصى للتخفيض (ر.س)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بداية الكوبون'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='نسبة الخصم'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=40, verbose_name='كود الكوبون'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_kind',
            field=models.CharField(choices=[('percent', 'نسبة من مجموع مشتريات العميل'), ('fixed', 'مبلغ ثابت')], max_length=10, verbose_name='نوع الخصم للعميل'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الكوبون'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد مرات الاستخدام للجميع'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_cart',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الحد الادنى من المشتريات (ر.س)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='per_customer_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد مرات الاستخدام للعميل الواحد'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['start_date'], name='coupons_cou_start_d_9e0133_idx'),
        ),
    ]
