# Generated by Django 5.2.6 on 2025-10-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_exclude_discounted_coupon_free_shipping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=40, verbose_name='Coupon Code'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_kind',
            field=models.CharField(choices=[('percent', 'Percentage of total purchases'), ('fixed', 'Fixed amount')], max_length=10, verbose_name='Discount Type'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='exclude_discounted',
            field=models.BooleanField(default=False, verbose_name='Exclude Discounted Products'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='free_shipping',
            field=models.BooleanField(default=False, verbose_name='Free Shipping'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maximum Discount Amount'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Total Uses'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_cart',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Minimum Cart Value'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='per_customer_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Uses Per Customer'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
