# Generated by Django 5.2.6 on 2025-09-09 19:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salla_order_id', models.CharField(max_length=100)),
                ('salla_customer_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('revenue_sar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('used_coupon_code', models.CharField(blank=True, max_length=40, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attribution',
                'verbose_name_plural': 'Attributions',
            },
        ),
        migrations.CreateModel(
            name='EmailSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('source', models.CharField(blank=True, max_length=60, null=True)),
                ('consent', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField()),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Subscriber',
                'verbose_name_plural': 'Email Subscribers',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('salla_event_id', models.CharField(blank=True, max_length=120, null=True)),
                ('payload', models.JSONField()),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('salla_merchant_id', models.CharField(help_text='Store ID in Salla', max_length=100, unique=True)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
            },
        ),
    ]
