# Generated by Django 5.2.6 on 2025-09-09 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('coupons', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='coupons.coupon'),
        ),
        migrations.AddField(
            model_name='attribution',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='notifications.notification'),
        ),
        migrations.CreateModel(
            name='SallaToken',
            fields=[
                ('merchant', models.OneToOneField(help_text='1:1 with merchant', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='salla_token', serialize=False, to='core.merchant')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('scope', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salla Token',
                'verbose_name_plural': 'Salla Tokens',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.merchant'),
        ),
        migrations.AddField(
            model_name='emailsubscriber',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_subscribers', to='core.merchant'),
        ),
        migrations.AddField(
            model_name='attribution',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='core.merchant'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['merchant'], name='core_event_merchan_9e500c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'occurred_at'], name='core_event_event_t_816c52_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailsubscriber',
            constraint=models.UniqueConstraint(fields=('merchant', 'email'), name='uq_email_per_merchant'),
        ),
        migrations.AddIndex(
            model_name='attribution',
            index=models.Index(fields=['occurred_at'], name='core_attrib_occurre_317471_idx'),
        ),
        migrations.AddConstraint(
            model_name='attribution',
            constraint=models.UniqueConstraint(fields=('merchant', 'salla_order_id'), name='uq_order_per_merchant'),
        ),
    ]
