# Generated by Django 5.2.6 on 2025-12-12 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merchant_is_connected'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetSettings',
            fields=[
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='widget_settings', serialize=False, to='core.merchant')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (Match Store)')], default='light', max_length=20)),
                ('primary_color', models.CharField(default='#17a8ff', help_text='Hex color code', max_length=7)),
                ('border_radius', models.IntegerField(default=12, help_text='Border radius in pixels')),
                ('max_products', models.IntegerField(default=4, help_text='Max products to show')),
                ('show_prices', models.BooleanField(default=True)),
                ('show_add_to_cart', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Widget Settings',
                'verbose_name_plural': 'Widget Settings',
            },
        ),
    ]
