# Generated by Django 5.2.6 on 2025-12-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_widgetsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer first name for purchase display', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='attribution',
            name='product_name',
            field=models.CharField(blank=True, help_text='Main product name for purchase display', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='WidgetSettings',
        ),
    ]
