# Generated by Django 5.2.6 on 2025-09-09 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=300)),
                ('viewed_at', models.DateTimeField()),
                ('referrer', models.CharField(blank=True, max_length=300, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='core.merchant')),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'indexes': [models.Index(fields=['merchant'], name='visitors_pa_merchan_605405_idx'), models.Index(fields=['session_id'], name='visitors_pa_session_659f55_idx'), models.Index(fields=['merchant', 'viewed_at'], name='visitors_pa_merchan_94dfc4_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('device', models.CharField(blank=True, max_length=40, null=True)),
                ('source', models.CharField(blank=True, max_length=80, null=True)),
                ('country', models.CharField(blank=True, max_length=80, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_sessions', to='core.merchant')),
            ],
            options={
                'verbose_name': 'Visitor Session',
                'verbose_name_plural': 'Visitor Sessions',
                'indexes': [models.Index(fields=['last_seen_at'], name='visitors_vi_last_se_f1e695_idx')],
                'constraints': [models.UniqueConstraint(fields=('merchant', 'session_id'), name='uq_session_per_merchant')],
            },
        ),
    ]
