# Generated by Django 5.2.6 on 2025-09-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "objective",
                    models.CharField(
                        choices=[
                            ("sales", "Increase Sales"),
                            ("awareness", "Brand Awareness"),
                            ("clearance", "Clearance"),
                        ],
                        default="sales",
                        max_length=50,
                    ),
                ),
                ("product_url", models.URLField()),
                (
                    "budget_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "primary_channel",
                    models.CharField(
                        choices=[
                            ("tiktok", "TikTok"),
                            ("instagram", "Instagram"),
                            ("snapchat", "Snapchat"),
                        ],
                        default="tiktok",
                        max_length=50,
                    ),
                ),
                ("status", models.CharField(default="draft", max_length=20)),
                ("external_ids", models.JSONField(blank=True, default=dict)),
                ("start_at", models.DateTimeField(auto_now_add=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
