# Generated by Django 5.2.6 on 2025-09-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='objective',
            field=models.CharField(choices=[('sales', 'Increase Sales'), ('awareness', 'Brand Awareness'), ('clearance', 'Clearance')], default='sales', max_length=32),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='primary_channel',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('snapchat', 'Snapchat')], default='tiktok', max_length=32),
        ),
    ]
