# Generated by Django 5.2.6 on 2025-10-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_alter_campaign_objective_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="external_ids",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
