# Generated by Django 5.2.6 on 2025-09-09 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'email'), ('sms', 'sms'), ('whatsapp', 'whatsapp'), ('push', 'push')], max_length=20)),
                ('template', models.TextField()),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.merchant')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'email'), ('sms', 'sms'), ('whatsapp', 'whatsapp'), ('push', 'push')], max_length=20)),
                ('salla_customer_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=254, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('body_rendered', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('sent', 'sent'), ('delivered', 'delivered'), ('failed', 'failed')], default='queued', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=150, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.merchant')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_scheduled', 'schedule_at'], name='notificatio_is_sche_903d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['notification'], name='notificatio_notific_aed5f7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['salla_customer_id'], name='notificatio_salla_c_074b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status'], name='notificatio_status_180d6e_idx'),
        ),
    ]
