# Generated by Django 5.2.6 on 2025-10-01 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('popup', 'Popup'), ('banner', 'Banner'), ('modal', 'Modal')], default='popup', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('show_delay', models.IntegerField(default=3, help_text='Delay in seconds before showing')),
                ('auto_close', models.BooleanField(default=True)),
                ('auto_close_delay', models.IntegerField(default=10, help_text='Auto close delay in seconds')),
                ('position', models.CharField(default='top-right', help_text='Position on screen', max_length=20)),
                ('background_color', models.CharField(default='#17a8ff', help_text='Hex color code', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', help_text='Hex color code', max_length=7)),
                ('button_text', models.CharField(blank=True, help_text='Optional button text', max_length=50)),
                ('button_url', models.URLField(blank=True, help_text='Optional button URL')),
                ('target_pages', models.TextField(blank=True, help_text='Comma-separated page patterns to show on')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popup_notifications', to='core.merchant')),
            ],
            options={
                'verbose_name': 'Popup Notification',
                'verbose_name_plural': 'Popup Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
